include: package:flutter_lints/flutter.yaml

linter:
  rules:
    unnecessary_this: false
    curly_braces_in_flow_control_structures: false
    prefer_double_quotes: true
    always_specify_types: true