include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"

linter:
  rules:
    prefer_double_quotes: true
    always_declare_return_types: true
    unnecessary_this: false
    curly_braces_in_flow_control_structures: false