name: chat_gpt_app
description: Versão do Chat GPT em mobile integrado com a API Chat completion.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  mobx: ^2.1.4
  flutter_mobx: ^2.0.6+5
  dio: ^5.1.1
  shared_preferences: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mobx_codegen: ^2.2.0
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  image_path: "assets/app-icon.png"
  android: "launcher_icon"
  # ios: "assets/app-icon.png"
  remove_alpha_ios: true
  min_sdk_android: 16
  web:
    generate: true
    image_path: "assets/app-icon.png"
    background_color: "#333541"
    theme_color: "#444653"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/openSans/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/openSans/OpenSans-Regular.ttf
          style: normal
        - asset: assets/fonts/openSans/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/openSans/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/openSans/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/openSans/OpenSans-ExtraBold.ttf
          weight: 800

    - family: Lato
      fonts:
        - asset: assets/fonts/lato/Lato-Thin.ttf
          weight: 100
        - asset: assets/fonts/lato/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/lato/Lato-Regular.ttf
          style: normal
        - asset: assets/fonts/lato/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/lato/Lato-Black.ttf
          weight: 900